### ISSUE TITLE
Laravel search only specific word 

### ISSUE THREAD

**Issue by tameemahmad** [atm-code/ar-php-laravel#7]
Hi ,
I have a database with arabic records now i want to search exact word like Words that include
شَهْر
But excluding
شَهْرَيْنِ

Words that include
سَنَة
And
سِنِين
Laravel approach
` Verse::where('text','like','%'.$string.'%')->get()`
Your Package 
`Verse::searchAr('text',$string)->get();`

your package also giving same result , i mean search for all similar words which contain شَهْر but i want to search where word is only شَهْر
any soultion or suggestion

**Comment by atmonshi** [comment]
as you know my package depends on the @khaled-alshamaa package
https://github.com/khaled-alshamaa/ar-php

try to pass the third parameter `searchAr('text',$string,'OR')`

also if can you print out the SQL statment by: `Verse::searchAr('text',$string)->toSql();`
so we can figer it out how we can achieve that!

**Comment by atmonshi** [comment]
I think if you only want the same word like `شَهْر` or `سَنَة `
it's safe to use laravel `where` directly.

the Idea of the package (ar-PHP) is to help search for all similar words like:

`شَهْرَيْنِ ` , `شَهْور` , `أشهر`, `اشهر`

**Comment by tameemahmad** [comment]
"select * from `verses` where ( REPLACE(ذَٰلِكَ, 'ـ', '') REGEXP 'text')" here is the sql result of my query

**Comment by tameemahmad** [comment]
Actually i want to search specific words in Quran i used many tricks and regular expressions its give me result but i want more result in depth like get the word سَنَةٌ to be more generic by removing the last vowel ٌ to become سَنَة so it will match all versions like سَنَةٍ etc

And then make it more generic to get السَنَة including بالسَنَة

**Comment by tameemahmad** [comment]
```
$results=\App\Models\Verse::with('surah')->where('text',$string)
        ->orwhere('text','REGEXP','(^|[[:space:]])'.$string.'[[:space:]]?')
        ->orwhere('text','LIKE','[[:<:]]'.$string.'[[:>:]]')
        ->orwhere('text','REGEXP','(^|[[:space:]])'.$string.'([[:space:]]|$)')->get();

this query gives me 80% of the results but still 20% is remain
```

**Comment by khaled-alshamaa** [comment]
Oops! It looks like I did not mention it here :-(

The stripHarakat method in version 6.2 of the Ar-PHP library (released on 20 Jun 2021) can remove the last Harakat alone:
* [Change log note](https://github.com/khaled-alshamaa/ar-php/blob/master/CHANGELOG.md#whats-new-in-arphp-620-release-date-jun-20-2021)
* [Method documentation](https://ar-php.org/github/docs/classes/ArPHP-I18N-Arabic.html#method_stripHarakat) 
* [Live example](https://ar-php.org/github/examples/standard.php)
